Update to 20210326

diff --git a/do-part b/do-part
--- a/do-part
+++ b/do-part
@@ -121,13 +121,18 @@ then
   cp -pR "$work"/lib/* "$lib/nontimecop"
   cp -pR "$work"/include/* "$include/nontimecop"
   
-  echo "=== `date` === building cpucycles for TIMECOP"
-  rm -rf "$work"
-  mkdir -p "$work"
-  cp -pR cpucycles/* "$work"
-  ( cd "$work" && env CPUCYCLESWRAPPER="killafter 300 valgrind" sh do )
-  cp -pR "$work"/lib/* "$lib/timecop"
-  cp -pR "$work"/include/* "$include/timecop"
+  if valgrind pwd >/dev/null 2>&1
+  then
+    echo "=== `date` === building cpucycles for TIMECOP"
+    rm -rf "$work"
+    mkdir -p "$work"
+    cp -pR cpucycles/* "$work"
+    ( cd "$work" && env CPUCYCLESWRAPPER="killafter 300 valgrind" sh do )
+    cp -pR "$work"/lib/* "$lib/timecop"
+    cp -pR "$work"/include/* "$include/timecop"
+  else
+    echo "=== `date` === skipping cpucycles for TIMECOP: valgrind not found"
+  fi
 
   echo "=== `date` === building kernelrandombytes"
   rm -rf "$work"
@@ -173,7 +178,7 @@ do
         echo "=== `date` === trying CC=$c CXX=$cpp CFLAGS=$copts CXXFLAGS=$cppopts ABI=$gmpabi"
         rm -rf "$work"
         mkdir -p "$work"
-        cp -pR gmp-6.2.0/* "$work"
+        cp -pR gmp/* "$work"
         ( cd "$work" \
           && ./configure --enable-cxx \
              ABI="$gmpabi" \
@@ -207,7 +212,7 @@ do
     echo "=== `date` === trying CXX=$cpp CXXFLAGS=$cppopts"
     rm -rf "$work"
     mkdir -p "$work"
-    cp -pR ntl-11.4.3/* "$work"
+    cp -pR ntl/* "$work"
     ( cd "$work/src" \
       && ./configure \
          CXX="$cpp" CXXFLAGS="$cppopts" \
@@ -269,7 +274,7 @@ do
     echo "=== `date` === trying CXX=$cpp CXXFLAGS=$cppopts"
     rm -rf "$work"
     mkdir -p "$work"
-    cp -pR cryptopp-820/* "$work"
+    cp -pR cryptopp/* "$work"
     ( cd "$work" \
       && make CXX="$cpp" CXXFLAGS="-DNDEBUG $cppopts" LDFLAGS="$cppopts" \
       && cp libcryptopp.a "$lib/$abi/libcryptopp.a" \
@@ -347,9 +352,22 @@ do
       [ -f "$lib/$abi/libcryptopp.a" ] && timecoplibs="$lib/$abi/libcryptopp.a $timecoplibs"
       [ -f "$lib/$abi/lib${project}.a" ] && timecoplibs="$lib/$abi/lib${project}.a $timecoplibs"
 
+      rslibs=`"oklibs-$abi" | tr ' ' '\012' | sed 's/-l//' | tr '\012' ' '`
+      rslibs="cpucycles $rslibs"
+      rslibs="kernelrandombytes $rslibs"
+      [ -f "$lib/$abi/libgmp.a" ] && rslibs="gmp $rslibs"
+      [ -f "$lib/$abi/libgmpxx.a" ] && rslibs="gmpxx $rslibs"
+      [ -f "$lib/$abi/libntl.a" ] && rslibs="ntl $rslibs"
+      [ -f "$lib/$abi/libkeccak.a" ] && rslibs="keccak $rslibs"
+      [ -f "$lib/$abi/libcryptopp.a" ] && rslibs="cryptopp $rslibs"
+      [ -f "$lib/$abi/lib${project}.a" ] && rslibs="${project} $rslibs"
+
       trylibs="$libs"
       timecoptrylibs="$timecoplibs"
+      rstrylibs="$rslibs"
       measurelibs="$libs"
+      rsmeasurelibs="$rslibs"
+
       userandombytes=0
       [ $o = crypto_scalarmult ] && userandombytes=1
       [ $o = crypto_box ] && userandombytes=1
@@ -361,7 +379,9 @@ do
       then
         trylibs="$lib/$abi/knownrandombytes.o $libs"
         timecoptrylibs="$lib/$abi/knownrandombytes.o $timecoplibs"
+        rstrylibs="knownrandombytes $rslibs"
         measurelibs="$lib/$abi/fastrandombytes.o $libs"
+        rsmeasurelibs="fastrandombytes $rslibs"
       fi
 
       rm -rf "$work"
@@ -465,7 +485,7 @@ do
           sfiles=`ls "$work/compile" | grep '\.[sS]$' || :`
           ccfiles=`ls "$work/compile" | grep '\.cc$' || :`
           cppfiles=`ls "$work/compile" | grep '\.cpp$' || :`
-  
+
           language=c
           [ "x$cppfiles" = x ] || language=cpp
           [ "x$ccfiles" = x ] || language=cpp
@@ -474,7 +494,11 @@ do
           cp -p "$o/measure.c" "$work/compile/measure.$language"
           cp -p "try-anything.c" "$work/compile/try-anything.$language"
           cp -p "measure-anything.c" "$work/compile/measure-anything.$language"
-  
+
+          ( echo '#define SMALL'
+            echo '#include "try.'"$language"'"'
+          ) > "$work/compile/try-small.$language"
+
           touch "$work/compile/test-more.inc"
           [ -f "$o/$p/supercop/test-more.inc" ] && cp -p "$o/$p/supercop/test-more.inc" "$work/compile/test-more.inc" || :
           touch "$work/compile/test-loops.inc"
@@ -482,7 +506,28 @@ do
   
           cp -p MACROS "$work/compile/MACROS"
           cp -p PROTOTYPES.c "$work/compile/PROTOTYPES.c"
-  
+
+          wanttimecop=''
+          if [ ${TIMECOP+yes} ] && [ "$security" = "constbranchindex" ]
+          then
+            wanttimecop=yes
+            ( echo '#define TIMECOP'
+              echo "#define TIMECOP_LOOPS $TIMECOP"
+              echo '#include "try.'"$language"'"'
+            ) > "$work/compile/try-timecop.$language"
+          fi
+
+          rust=''
+          if [ -f "$work/compile/Cargo.toml" ]
+          then
+            rust=yes
+            sed -i 's/int main/int c_main/' \
+              "$work/compile/try-anything.$language" \
+              "$work/compile/measure-anything.$language"
+            cp -pr rusthooks "$work/compile/rusthooks"
+          fi
+          # XXX: also support standalone *.rs via okrs-${abi}
+
           (
             cd "$work/compile"
 
@@ -534,15 +579,32 @@ do
                 echo "#endif"
               ) > "$opp.h"
             done
+
+            if [ "$rust" ]
+            then
+              mkdir -p src/bin
+              supercop-bin-rs "$o" "$op" "$opi" try-anything try-small $rstrylibs > src/bin/try-small.rs
+              supercop-bin-rs "$o" "$op" "$opi" try-anything try $rstrylibs > src/bin/try.rs
+              supercop-bin-rs "$o" "$op" "$opi" measure-anything measure $rsmeasurelibs > src/bin/measure.rs
+              supercop-cargo-extra >> Cargo.toml
+              if [ "$wanttimecop" ]
+              then
+                supercop-bin-rs "$o" "$op" "$opi" try-anything try-timecop $rstrylibs > src/bin/try-timecop.rs
+                timecop-cargo-extra >> Cargo.toml
+              fi
+            fi
   
             ok${language}-$abi \
-            | while read compiler
+            | while read compilerbin compileropts
             do
+              compiler="$compilerbin $compileropts"
               echo "=== `date` === $abi $implementationdir $security $compiler"
               compilerword=`echo "$compiler" | tr ' ' '_'`
               ok=1
+              madeo=0
               for f in $cfiles $sfiles $ccfiles $cppfiles
               do
+                madeo=1
                 if [ "$ok" = 1 ]
                 then
                   $compiler -DSUPERCOP \
@@ -569,22 +631,56 @@ do
               done
   
               [ "$ok" = 1 ] || continue
-              okar-$abi cr "$op.a" *.o || continue
-              ranlib "$op.a"
-  
-              killafter 300 \
-              $compiler -DSUPERCOP -DSMALL \
-                $includes \
-                -o try try.$language try-anything.$language \
-                "$op.a" $trylibs >../errors 2>&1 || ok=0
-              cat ../errors \
-              | while read err
-              do
-                echo "$version $shorthostname $abi $startdate $o $p/$security fromcompiler $implementationdir $compilerword try.$language $err" >&5
-              done
+              if [ "$madeo" = 1 ]
+              then
+                okar-$abi cr "lib$op.a" *.o || continue
+              else
+                okar-$abi cr "lib$op.a" || continue
+              fi
+              ranlib "lib$op.a" || :
+
+              if [ "$rust" ]
+              then
+                supercop-build-rs "$op" "$lib/$abi" "$lib/nontimecop/$abi" > build.rs
+                if killafter 300 \
+                   env \
+                   CC="$compilerbin" \
+                   CFLAGS="$compileropts $includes -DSUPERCOP -DCOMPILER=\"$compilerword\"" \
+                   RUSTFLAGS='-C target_cpu=native' \
+                   cargo build -q --release --bin try-small --bin try --bin measure >../errors 2>&1
+                then
+                  cp target/release/try-small try-small || ok=0
+                  cp target/release/try try || ok=0
+                  cp target/release/measure measure || ok=0
+                  strip try-small try measure || :
+                else
+                  ok=0
+                fi
+                cat ../errors \
+                | while read err
+                do
+                  echo "$version $shorthostname $abi $startdate $o $p/$security fromcompiler $implementationdir $compilerword try.$language $err" >&5
+                done
+                cargo clean -q
+              fi
+              [ "$ok" = 1 ] || continue
+
+              if [ ! "$rust" ]
+              then
+                killafter 300 \
+                $compiler -DSUPERCOP \
+                  $includes \
+                  -o try-small try-small.$language try-anything.$language \
+                  "lib$op.a" $trylibs >../errors 2>&1 || ok=0
+                cat ../errors \
+                | while read err
+                do
+                  echo "$version $shorthostname $abi $startdate $o $p/$security fromcompiler $implementationdir $compilerword try.$language $err" >&5
+                done
+              fi
               [ "$ok" = 1 ] || continue
   
-              if sh -c 'killafter 3600 ./try || exit $?' >../outputs 2>../errors
+              if sh -c 'killafter 3600 ./try-small || exit $?' >../outputs 2>../errors
               then
                 checksumsmall=`awk '{print $1}' < ../outputs`
                 cycles=`awk '{print $2}' < ../outputs`
@@ -606,16 +702,19 @@ do
               && echo "$version $shorthostname $abi $startdate $o $p/$security try $checksumsmall fails $cycles $checksumcycles $cyclespersecond $impl $compilerword" >&5 \
               && continue
   
-              killafter 300 \
-              $compiler -DSUPERCOP \
-                $includes \
-                -o try try.$language try-anything.$language \
-                "$op.a" $trylibs >../errors 2>&1 || ok=0
-              cat ../errors \
-              | while read err
-              do
-                echo "$version $shorthostname $abi $startdate $o $p/$security fromcompiler $implementationdir $compilerword try.$language $err" >&5
-              done
+              if [ ! "$rust" ]
+              then
+                killafter 300 \
+                $compiler -DSUPERCOP \
+                  $includes \
+                  -o try try.$language try-anything.$language \
+                  "lib$op.a" $trylibs >../errors 2>&1 || ok=0
+                cat ../errors \
+                | while read err
+                do
+                  echo "$version $shorthostname $abi $startdate $o $p/$security fromcompiler $implementationdir $compilerword try.$language $err" >&5
+                done
+              fi
               [ "$ok" = 1 ] || continue
   
               if sh -c 'killafter 3600 ./try || exit $?' >../outputs 2>../errors
@@ -647,22 +746,50 @@ do
   
               compiledinfo "$version" "$shorthostname" "$abi" "$startdate" "$o" "$p/$security" "$implementationdir" "$compilerword" "$opi" "$language"
 
-              if [ ${TIMECOP+yes} ] && [ "$security" = "constbranchindex" ]
+              if [ "$wanttimecop" ]
               then
                 ok=1
-                killafter 300 \
-                $compiler -DSUPERCOP -DTIMECOP -DTIMECOP_LOOPS="$TIMECOP" \
-                  $timecopincludes \
-                  -o try try.$language try-anything.$language \
-                  "$op.a" $timecoptrylibs >../errors 2>&1 || ok=0
-                cat ../errors \
-                | while read err
-                do
-                  echo "$version $shorthostname $abi $startdate $o $p/$security fromcompiler $implementationdir $compilerword try.$language $err" >&5
-                done
+
+                if [ "$rust" ]
+                then
+                  timecop-build-rs "$op" "$lib/$abi" "$lib/timecop/$abi" > build.rs
+                  if killafter 300 \
+                     env \
+                     CC="$compilerbin" \
+                     CFLAGS="$compileropts $timecopincludes -DSUPERCOP -DCOMPILER=\"$compilerword\"" \
+                     RUSTFLAGS='-C target_cpu=native' \
+                     cargo build -q --release --bin try-timecop >../errors 2>&1
+                  then
+                    cp target/release/try-timecop try-timecop || ok=0
+                    strip try-timecop || :
+                  else
+                    ok=0
+                  fi
+                  cat ../errors \
+                  | while read err
+                  do
+                    echo "$version $shorthostname $abi $startdate $o $p/$security fromcompiler $implementationdir $compilerword try.$language $err" >&5
+                  done
+                  cargo clean -q
+                fi
                 [ "$ok" = 1 ] || continue
 
-                if sh -c 'killafter 360 valgrind -q --error-exitcode=99 --track-origins=yes ./try || exit $?' >../outputs 2>../errors
+                if [ ! "$rust" ]
+                then
+                  killafter 300 \
+                  $compiler -DSUPERCOP \
+                    $timecopincludes \
+                    -o try-timecop try-timecop.$language try-anything.$language \
+                    "lib$op.a" $timecoptrylibs >../errors 2>&1 || ok=0
+                  cat ../errors \
+                  | while read err
+                  do
+                    echo "$version $shorthostname $abi $startdate $o $p/$security fromcompiler $implementationdir $compilerword try.$language $err" >&5
+                  done
+                fi
+                [ "$ok" = 1 ] || continue
+
+                if sh -c 'killafter 600 valgrind -q --error-exitcode=99 --track-origins=yes ./try-timecop || exit $?' >../outputs 2>../errors
                 then
                   echo "$version $shorthostname $abi $startdate $o $p/$security timecop_pass $implementationdir $compilerword $TIMECOP $?" >&5
                   word=timecop_output
@@ -688,28 +815,33 @@ do
               [ -s "../constbranchindex/bestc/median" ] && [ `cat "../constbranchindex/bestc/median"` -le $cycles ] && continue
               [ -s "../$security/bestc/median" ] && [ `cat "../$security/bestc/median"` -le $cycles ] && continue
   
-              killafter 3600 \
-              $compiler -D'COMPILER="'"$compiler"'"' \
-                -DSUPERCOP -DLOOPS=3 \
-                $includes \
-                -o measure measure.$language measure-anything.$language \
-                "$op.a" $measurelibs >../errors 2>&1 || ok=0
-              cat ../errors \
-              | while read err
-              do
-                echo "$version $shorthostname $abi $startdate $o $p/$security fromcompiler $implementationdir $compilerword measure.$language $err" >&5
-              done
+              if [ ! "$rust" ]
+              then
+                killafter 3600 \
+                $compiler -D'COMPILER="'"$compiler"'"' \
+                  -DSUPERCOP -DLOOPS=3 \
+                  $includes \
+                  -o measure measure.$language measure-anything.$language \
+                  "lib$op.a" $measurelibs >../errors 2>&1 || ok=0
+                cat ../errors \
+                | while read err
+                do
+                  echo "$version $shorthostname $abi $startdate $o $p/$security fromcompiler $implementationdir $compilerword measure.$language $err" >&5
+                done
+              fi
               [ "$ok" = 1 ] || continue
     
               for b in best bestc
               do
                 [ $language = cpp ] && [ $b = bestc ] && continue
+                [ "$rust" ] && [ $b = bestc ] && continue
                 [ -s "../constbranchindex/$b/median" ] && [ `cat "../constbranchindex/$b/median"` -le $cycles ] && continue
                 [ -s "../$security/$b/median" ] && [ `cat "../$security/$b/median"` -le $cycles ] && continue
                 echo "$cycles" > ../"$security/$b/median"
                 rm -f ../$security/$b/*.o ../$security/$b/measure || continue
                 for f in *.o
                 do
+                  [ -f "$f" ] || continue
                   cp -p "$f" "../$security/$b/${opi}-$f"
                 done
                 cp -p "${op}_publicinputs.h" "../$security/$b/${op}_publicinputs.h"
@@ -782,7 +914,9 @@ do
 
       ( cd "$work" \
         && env abi="$abi" libs="$libs" include="$includes" sh do \
-        && cp -p "lib/$abi/knownrandombytes.o" "$lib/$abi/knownrandombytes.o"
+        && cp -p "lib/$abi/knownrandombytes.o" "$lib/$abi/knownrandombytes.o" \
+        && okar-$abi cr "$lib/$abi/libknownrandombytes.a" "$lib/$abi/knownrandombytes.o" \
+        && ( ranlib "$lib/$abi/libknownrandombytes.a" || exit 0 )
       )
 
       echo "=== `date` === $abi fastrandombytes"
@@ -793,7 +927,9 @@ do
 
       ( cd "$work" \
         && env abi="$abi" libs="$libs" include="$includes" sh do \
-        && cp -p "lib/$abi/fastrandombytes.o" "$lib/$abi/fastrandombytes.o"
+        && cp -p "lib/$abi/fastrandombytes.o" "$lib/$abi/fastrandombytes.o" \
+        && okar-$abi cr "$lib/$abi/libfastrandombytes.a" "$lib/$abi/fastrandombytes.o" \
+        && ( ranlib "$lib/$abi/libfastrandombytes.a" || exit 0 )
       )
     done
   fi
